#!/bin/bash -l 
#SBATCH -p normal
#SBATCH -n 192
#SBATCH -N 24
#SBATCH -t 00:10:00 
#SBATCH -J multi-HW3
#SBATCH -o multi-HW3.%j.out
#SBATCH -e multi-HW3.%j.err

# Specify path to your input file here
INPUT=test

cd ${PWD}
for P in 16 32 64 96 120 144 168 192; do
	tacc-upcrun -np $P -shared-heap=1G ./pgen ${INPUT}
done
